apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: smart-tender
type: Opaque
stringData:
  username: tender_user
  password: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: smart-tender
type: Opaque
stringData:
  secret: SmartTenderSecretKeyMustBe256BitsLongForHS256Algorithm!
